const products = [
  {
    _id: '1',
    name: 'Ankara1',
    image: '',
    description: 'Ankara1',
    brand: 'Rossy design',
    price: 4000,
    countInStock: 0,
    rating: 5,
    numReviews: 4,
  },
  {
    _id: '2',
    name: 'Ankara2',
    image: '',
    description: 'Ankara2',
    brand: 'Rossy design',
    price: 5000,
    countInStock: 5,
    rating: 5,
    numReviews: 5,
  },
  {
    _id: '3',
    name: 'Ankara3',
    image: '',
    description: 'Ankara3',
    brand: 'Rossy design',
    price: 4500,
    countInStock: 9,
    rating: 5,
    numReviews: 4.5,
  },
  {
    _id: '4',
    name: 'Ankara4',
    image: '',
    description: 'Ankara4',
    brand: 'Rossy design',
    price: 6000,
    countInStock: 7,
    rating: 5,
    numReviews: 5,
  },
  {
    _id: '5',
    name: 'Ankara5',
    image: '',
    description: 'Ankara5',
    brand: 'Rossy design',
    price: 5000,
    countInStock: 2,
    rating: 5,
    numReviews: 4,
  },
];
